### ISSUE TITLE
Get feedback on report designs from Neely and Larry

### ISSUE THREAD

**Issue by selimnairb** [ResearchSoftwareInstitute/ginotebook#13]
- 97 percent complete

If you  are this task's owner, select the pencil icon in the upper right of this box to edit and increase this percent periodically as you make progress on this task (don't change the _\* nn percent complete_ formatting though). This value will be automatically propagated to the [GI Venture Dashboard](http://distribution.hydroshare.org/rayi/giventure/) below.

[CLICK HERE FOR THE GI VENTURE %COMPLETE DASHBOARD VIEW OF ALL TASKS](http://distribution.hydroshare.org/rayi/giventure/) 

---

**Comment by BardiaHeidari** [comment]
Got feedback from Neely during CyberSEES call on 08/13. Need to use annual volume reduction per treated area for report.

**Comment by selimnairb** [comment]
@BardiaHeidari please update the percent complete and close this issue if it is done.

**Comment by BardiaHeidari** [comment]
We got feedback on the variables needed to be included in the GI performance report and have a clear grasp of what to include in the report. The report will include spider plots for monetary benefits of air pollutant removal per year, life cycle cost, annual runoff reduction per treated area, property value increase, and human preference score. The report skeleton is %80 complete. The only remaining issue is the comparison between results for RHESSys for baseline and raingarden scenarios, which is counter intuitive to actual GI performance . If by 08/22 the issue is not solved, we will include results of stormwater volume reduction calculated by RHESSys and previously used in Brian's thesis.

**Comment by SammyRivera** [comment]
Addressed here: https://github.com/ResearchSoftwareInstitute/ginotebook/issues/14

![screen shot 2015-08-21 at 12 29 48 pm](https://cloud.githubusercontent.com/assets/3780858/9414762/9138a7a0-4800-11e5-9f01-757525457259.png)

**Comment by SammyRivera** [comment]
Update on GI Report Muck-up: 97%. We only need to populated it with the demo data and get feedback on wording, labels, titles, etc.
![screen shot 2015-08-27 at 11 09 46 pm](https://cloud.githubusercontent.com/assets/3780858/9539010/bf03c4de-4d10-11e5-99a0-db006651c41c.png)
![screen shot 2015-08-27 at 11 04 32 pm](https://cloud.githubusercontent.com/assets/3780858/9538977/61b7ab24-4d10-11e5-8703-968eac1ec9dc.png)

**Comment by selimnairb** [comment]
@SammyRivera Let me know when the HTML, CSS/or JS assets for this are ready.  Thanks!

**Comment by BardiaHeidari** [comment]
The report is finalized with realistic results and have been sent to Brian via email.
